### ISSUE TITLE
这项目应该怎么编译呢

### ISSUE THREAD

**Issue by thouger** [null-luo/btrace#1]
文章里说，参考https://github.com/cilium/ebpf/tree/main/examples 的编译，可是我用这个项目的编译方式，分别是：
1. make -C ../ 提示
```
❯ make -C ../
make: Entering directory '/home/thouger/Desktop/code/btrace'
go run github.com/cilium/ebpf/cmd/bpf2go -go-package main --target=arm64 -type event bpf binder_transaction.byte.c -- -I./headers
Compiled /home/thouger/Desktop/code/btrace/bpf_arm64_bpfel.o
Stripped /home/thouger/Desktop/code/btrace/bpf_arm64_bpfel.o
Wrote /home/thouger/Desktop/code/btrace/bpf_arm64_bpfel.go
go mod tidy
go: downloading github.com/google/go-cmp v0.5.9
go: downloading github.com/go-quicktest/qt v1.101.0
go: downloading github.com/kr/pretty v0.3.1
go: downloading github.com/kr/text v0.2.0
go: downloading github.com/rogpeppe/go-internal v1.11.0
go build
# btrace
./main.go:44:10: undefined: bpfObjects
./main.go:45:12: undefined: loadBpfObjects
./main.go:80:12: undefined: bpfEvent
make: *** [Makefile:21: build] Error 1
make: Leaving directory '/home/thouger/Desktop/code/btrace'
```
2. 用go build 方式
```
❯ go build
# btrace
./main.go:44:10: undefined: bpfObjects
./main.go:45:12: undefined: loadBpfObjects
./main.go:80:12: undefined: bpfEvent
```

**Comment by thouger** [comment]
然后我又尝试将它放到cilium/ebpf 项目下的 examples，然后执行命令
```
thouger in 🌐 thouger-ubuntu in btrace on  main [?] via C v11.4.0-gcc via 🐹 v1.22.4
❯ go generate
Compiled /home/thouger/Desktop/code/cilium-eBP/examples/btrace/bpf_arm64_bpfel.o
Stripped /home/thouger/Desktop/code/cilium-eBP/examples/btrace/bpf_arm64_bpfel.o
Wrote /home/thouger/Desktop/code/cilium-eBP/examples/btrace/bpf_arm64_bpfel.go

thouger in 🌐 thouger-ubuntu in btrace on  main [?] via C v11.4.0-gcc via 🐹 v1.22.4
❯ go build
# btrace
./main.go:44:10: undefined: bpfObjects
./main.go:45:12: undefined: loadBpfObjects
./main.go:80:12: undefined: bpfEvent
```
感觉还是没成功

**Comment by thouger** [comment]
分别在 x64 和 arm64 机器上测试

**Comment by null-luo** [comment]
编译方法更新到了readme文件里

**Comment by thouger** [comment]
尝试编译一下，编译成功，但是运行不了，在有 root 环境下测试也是一样，可能因为我是 m1 mac 环境的原因，等以后有 arm linux 环境再编译
`
(base) ╭─[~/Documents/code/btrace]─[thouger@thouger]─[0]─[2080]
╰─[:)] % make
go run github.com/cilium/ebpf/cmd/bpf2go -go-package main --target=arm64 -type trace_event -type trace_config bpf binder_transaction.byte.c -- -I./headers
Compiled /Users/thouger/Documents/code/btrace/bpf_arm64_bpfel.o
Stripped /Users/thouger/Documents/code/btrace/bpf_arm64_bpfel.o
Wrote /Users/thouger/Documents/code/btrace/bpf_arm64_bpfel.go
go mod tidy
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading golang.org/x/sys v0.15.0
go: downloading github.com/google/go-cmp v0.5.9
go: downloading github.com/go-quicktest/qt v1.101.0
go: downloading github.com/kr/pretty v0.3.1
go: downloading github.com/rogpeppe/go-internal v1.11.0
go: downloading github.com/kr/text v0.2.0
go build
(base) ╭─[~/Documents/code/btrace]─[thouger@thouger]─[0]─[2081]
╰─[:)] % fd btrace
btrace
(base) ╭─[~/Documents/code/btrace]─[thouger@thouger]─[0]─[2082]
╰─[:)] % adb push btrace /data/local/tmp
adb: error: failed to get feature set: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.
(base) ╭─[~/Documents/code/btrace]─[thouger@thouger]─[1]─[2083]
╰─[:(] % adb push btrace /data/local/tmp
btrace: 1 file pushed, 0 skipped. 78.3 MB/s (5553554 bytes in 0.068s)
(base) ╭─[~/Documents/code/btrace]─[thouger@thouger]─[0]─[2083]
╰─[:)] % adb shell
oriole:/ $ ^C
130|oriole:/ $ ^D
(base) ╭─[~/Documents/code/btrace]─[thouger@thouger]─[130]─[2084]
╰─[:(] % adb shell
oriole:/ $ cd /data/local/tmp
oriole:/data/local/tmp $ chmod 777 btrace
oriole:/data/local/tmp $ ./tr
/system/bin/sh: ./tr: inaccessible or not found
127|oriole:/data/local/tmp $ ./trace
/system/bin/sh: ./trace: inaccessible or not found
127|oriole:/data/local/tmp $ ./btrace
./btrace[1]: syntax error: unexpected '('
1|oriole:/data/local/tmp $ file btrace
btrace: Mach-O 64-bit arm64 executable
oriole:/data/local/tmp $ ./btrace -h
./btrace[1]: syntax error: unexpected '('
`

**Comment by kuekiko** [comment]
@thouger 使用NDK编译，自己下修改makefile就OK
```makefile
GO_RUN = go run github.com/cilium/ebpf/cmd/bpf2go
GO_MOD_TIDY = go mod tidy
GO_BUILD = go build
TARGET = arm64
PACKAGE = main
TYPE1 = trace_event
TYPE2 = trace_config
BPF_FILE = binder_transaction.byte.c
HEADERS = ./headers
BPF_OUTPUT = bpf
BINARY_NAME = btrace

## Android
CC = "${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android33-clang"
CXX = "${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android33-clang++"
GOOS = android
GOARCH = arm64
CGO_ENABLED = 1

all: bpf tidy build

bpf:
	$(GO_RUN) -go-package $(PACKAGE) --target=$(TARGET) -type $(TYPE1) -type $(TYPE2) $(BPF_OUTPUT) $(BPF_FILE) -- -I$(HEADERS)

tidy:
	$(GO_MOD_TIDY)

build: tidy
	CC=$(CC) CXX=$(CXX) GOOS=$(GOOS) GOARCH=$(GOARCH) CGO_ENABLED=$(CGO_ENABLED) $(GO_BUILD)

clean:
	rm -f $(BPF_OUTPUT)_$(TARGET)_bpfel.go $(BPF_OUTPUT)_$(TARGET)_bpfel.o $(BINARY_NAME)

.PHONY: all bpf tidy build clean
```

**Comment by thouger** [comment]
感谢，用m1 编译确实会有点问题，后来我在m1上的arm ubuntu编译后是可以正常运行的
